OutputDir: 'output'
STAR_THREADS: 30
bcftools_threads: 7
haplotypeCaller_threads: 7
##Specify file type: fastq,fq or SRA.
FileType: 'SRA'
##chromosomes to be genotyped
#Specify individual chromosome: ['5']
#Specify individual chromosomes: ['5','6']
#Specify all chromosomes 1-22: 'All' 
#Specify X,Y,M chromosomes in AllVar or Somatatic mode: ['X','Y','M']
#Specify all chromosomes 1-22 and X,Y,M in AllVar or Somatatic mode: 'AllMYX'
Interval: 'All'
##Specify number of PCs for machine learning step
PCs: 20
